[package]
name = "cannon-rs"
description = "Binary crate for cannon-rs"
edition = "2021"

version.workspace = true
authors.workspace = true

[dependencies]
# workspace
anyhow.workspace = true
alloy-primitives.workspace = true
serde.workspace = true
serde_json.workspace = true

# External
clap = { version = "4.5.9", features = ["derive"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"

# Local
cannon = { path = "../crates/cannon" }
cannon-fpvm = { path = "../crates/fpvm" }

[[bin]]
name = "cannon"
path = "src/cannon.rs"
